# -*- coding: utf-8 -*-
"""imagepreprocessing.pynb.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WwGRqKRImYFYK7F_oIlApVjaQXr3tYkL
"""

from skimage.io import imread
import matplotlib.pyplot as plt
import numpy as np

live = imread('/content/-Apple-.jpg')
mask = imread('/content/tomato.jpg')

plt.figure(figsize=(10, 10))
plt.subplot(121), plt.imshow(live, cmap='gray')
plt.subplot(122), plt.imshow(mask, cmap='gray')
plt.show()

plt.figure(figsize=(10, 10))
plt.subplot(121), plt.imshow(live, cmap='gray')
plt.subplot(122), plt.imshow(live - 20, cmap='gray')
plt.show()

shaded = imread('/content/-Apple-.jpg')
shading = imread('/content/tomato.jpg')

plt.figure(figsize=(10, 10))
plt.subplot(121), plt.imshow(shaded, cmap='gray')
plt.subplot(122), plt.imshow(shading, cmap='gray')
plt.show()

# Test on the X-ray dental image
xray = imread('/content/-Apple-.jpg')
mask_xray = imread('/content/tomato.jpg')

plt.figure(figsize=(10, 10))
plt.subplot(121), plt.imshow(xray, cmap='gray')
plt.subplot(122), plt.imshow(mask_xray, cmap='gray')
plt.show()

# Test on another image
scan = imread('/content/cotton.jpg')
print(scan.shape)

# Showing the body scan image
plt.figure(figsize=(7, 7))
plt.imshow(scan, cmap='gray')
plt.show()

plt.figure(figsize=(10, 10))
plt.subplot(211), plt.imshow(xray, cmap='gray')
plt.subplot(212), plt.plot(np.histogram(xray, bins=256)[0])
plt.show()